name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build and Publish to Public Repository
        run: npm run build && npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_PAT }}
